# Generated by Django 2.2.11 on 2022-07-28 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='imageLink',
        ),
    ]
