# Generated by Django 4.0.6 on 2022-07-28 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_id_alter_comment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='imageLink',
            field=models.CharField(default='static/default.png', max_length=255),
        ),
    ]
