# Generated by Django 2.2.11 on 2022-07-28 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_book_imagelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='imageLink',
            field=models.CharField(default='static/default.png', max_length=2255),
        ),
    ]
