# Generated by Django 4.0.6 on 2022-07-28 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_imagelink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='imageLink',
            field=models.CharField(default='static/default.png', max_length=1255),
        ),
    ]
