# Generated by Django 4.0.6 on 2022-07-28 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_remove_book_imagelink_alter_book_id_alter_comment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='imageLink',
            field=models.CharField(default='static/default.png', max_length=2255),
        ),
    ]
