# Generated by Django 4.0.6 on 2022-07-26 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_remove_book_comments_remove_book_date_finished_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='reading',
        ),
    ]
