# Generated by Django 2.2.11 on 2022-07-27 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20220727_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('Reading', 'Reading'), ('Completed', 'Completed'), ('Abandoned', 'Abandoned')], default='Reading', max_length=100),
        ),
    ]
